# Generated by Django 4.2.30 on 2026-08-06 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.CharField(max_length=16, primary_key=True, serialize=False, verbose_name='编号')),
                ('date', models.CharField(db_index=True, max_length=8, verbose_name='推荐日期')),
                ('slug', models.SlugField(blank=True, max_length=120, null=True, unique=True, verbose_name='别名')),
                ('zh_title', models.CharField(max_length=200, verbose_name='中文名')),
                ('en_title', models.CharField(blank=True, max_length=300, verbose_name='英文名')),
                ('year', models.CharField(blank=True, max_length=8, verbose_name='年份')),
                ('tagline', models.TextField(blank=True, verbose_name='标语')),
                ('meta', models.TextField(blank=True, verbose_name='导演/主演')),
                ('ratings', models.JSONField(blank=True, default=list, verbose_name='评分')),
                ('plot', models.JSONField(blank=True, default=list, verbose_name='剧情段落')),
                ('spoiler_note', models.TextField(blank=True, verbose_name='无剧透说明')),
                ('highlights', models.JSONField(blank=True, default=list, verbose_name='六大亮点')),
                ('quotes', models.JSONField(blank=True, default=list, verbose_name='台词（冗余）')),
                ('why', models.JSONField(blank=True, default=list, verbose_name='为什么值得一看')),
                ('honors', models.JSONField(blank=True, default=list, verbose_name='荣誉')),
                ('archive', models.JSONField(blank=True, default=list, verbose_name='影片档案')),
                ('review', models.TextField(blank=True, verbose_name='编辑评语')),
                ('review_by', models.CharField(blank=True, max_length=200, verbose_name='评语署名')),
                ('review_stars', models.PositiveSmallIntegerField(default=5, verbose_name='星级')),
                ('poster_svg', models.TextField(blank=True, verbose_name='海报 SVG')),
                ('poster_caption', models.CharField(blank=True, max_length=300, verbose_name='海报说明')),
                ('status', models.CharField(choices=[('published', '已发布'), ('draft', '草稿')], db_index=True, default='draft', max_length=20, verbose_name='状态')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='发布时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '电影推荐',
                'verbose_name_plural': '电影推荐',
                'ordering': ['-date'],
                'permissions': [('can_publish_movie', '可以发布/下线电影')],
            },
        ),
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('key', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='键')),
                ('value', models.JSONField(blank=True, default=dict, verbose_name='值')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '站点配置',
                'verbose_name_plural': '站点配置',
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_zh', models.TextField(verbose_name='台词')),
                ('quote_en', models.TextField(blank=True, verbose_name='英文台词')),
                ('speaker', models.CharField(blank=True, max_length=200, verbose_name='说话人')),
                ('context', models.TextField(blank=True, verbose_name='场景背景')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='标签')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_items', to='movies.movie', verbose_name='电影')),
            ],
            options={
                'verbose_name': '经典台词',
                'verbose_name_plural': '经典台词',
                'ordering': ['movie', 'id'],
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='标题')),
                ('caption', models.CharField(blank=True, max_length=300, verbose_name='说明')),
                ('image_url', models.URLField(verbose_name='图片地址')),
                ('bucket', models.CharField(choices=[('posters', '海报'), ('stills', '剧照'), ('covers', '封面'), ('svg-arts', '手绘 SVG')], default='stills', max_length=30, verbose_name='分类')),
                ('alt_text', models.CharField(blank=True, max_length=300, verbose_name='替代文本')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='标签')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_items', to='movies.movie', verbose_name='电影')),
            ],
            options={
                'verbose_name': '电影图片',
                'verbose_name_plural': '电影图片',
                'ordering': ['movie', 'sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='标题')),
                ('subtitle', models.CharField(blank=True, max_length=300, verbose_name='副标题')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='别名')),
                ('cover_url', models.URLField(blank=True, verbose_name='封面图')),
                ('summary', models.TextField(blank=True, verbose_name='摘要')),
                ('body_md', models.TextField(verbose_name='正文 Markdown')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='标签')),
                ('status', models.CharField(choices=[('published', '已发布'), ('draft', '草稿')], db_index=True, default='draft', max_length=20, verbose_name='状态')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='发布时间')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='浏览量')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='movies.movie', verbose_name='电影')),
            ],
            options={
                'verbose_name': '电影解析',
                'verbose_name_plural': '电影解析',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
